# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='null', upload_to='productos/imagenes'),
        ),
    ]
