# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170826_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.RenameModel(
            old_name='Marca',
            new_name='Fabricante',
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'verbose_name': 'Fabricante', 'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Modelo', verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Fabricante'),
        ),
    ]
