# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170827_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='anio_fin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anio_fin', to='main.Anio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='anio_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anio_inicio', to='main.Anio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='main.Modelo'),
        ),
    ]
