# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170827_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('motor', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='productos/imagenes')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anio_vehiculo', to='main.Anio')),
            ],
            options={
                'verbose_name': 'Descripcion',
                'verbose_name_plural': 'Descripcion Producto',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='anio_fin',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='anio_inicio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='motor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
        migrations.AddField(
            model_name='descripcion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_nombre', to='main.Producto'),
        ),
    ]
