# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170829_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='anio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anio_inicio', to='main.Anio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/imagenes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='motor',
            field=models.CharField(max_length=50),
        ),
    ]
