# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170829_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
