# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_producto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
