# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170831_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetaleProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('motor', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='productos/imagenes')),
                ('anio_fin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anio_fin', to='main.Anio')),
                ('anio_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anio_inicio', to='main.Anio')),
            ],
            options={
                'verbose_name': 'DetaleProducto',
                'verbose_name_plural': 'Detalle Producto',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='anio_fin',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='anio_inicio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='motor',
        ),
        migrations.AddField(
            model_name='detaleproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='main.Producto'),
        ),
    ]
