# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170831_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetaleProducto',
            new_name='DetalleProducto',
        ),
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'verbose_name': 'DetalleProducto', 'verbose_name_plural': 'Detalle Producto'},
        ),
    ]
