# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170831_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitproducto',
            name='imagen',
            field=models.ImageField(default='safsd', upload_to='kits/imagenes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
