# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170831_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitproducto',
            name='codigo',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
